services:
  web:
    container_name: quickquote
    build:
      context: .
      dockerfile: Dockerfile
    image: quickquote:latest
    ports:
      - "8080:80"         # host:container
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
