services:
  web-dev:
    image: node:20-alpine
    container_name: quickquote-dev
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5173/ >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  node_modules: {}

