name: Pages

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Ensure Pages site exists (create if missing)
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            try {
              await github.rest.pages.get({ owner, repo });
              core.info('Pages site already exists.');
            } catch (e) {
              if (e.status === 404) {
                core.info('Pages site not found; creating with build_type=workflow...');
                await github.request('POST /repos/{owner}/{repo}/pages', {
                  owner,
                  repo,
                  build_type: 'workflow',
                });
                core.info('Pages site created.');
              } else {
                throw e;
              }
            }
      - name: Configure Pages (auto-enable)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
